# Generated by Django 5.1.3 on 2024-11-26 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "when_to_perform",
                    models.TimeField(
                        help_text="Часы:Минуты:Секунды",
                        verbose_name="Когда необходимо выполнить",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=20, verbose_name="Место выполнения"),
                ),
                (
                    "act",
                    models.CharField(
                        max_length=50,
                        verbose_name="Действие, которое подразумевает привычку",
                    ),
                ),
                (
                    "pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Признак приятной привычки",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Частота выполнения привычки (в днях)"
                    ),
                ),
                (
                    "Reward",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.TimeField(
                        help_text="Часы:Минуты:Секунды",
                        verbose_name="Время, которое затрачивается на выполнение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Признак публичности привычки",
                        verbose_name="Публичность привычки",
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habits",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
        ),
    ]
