# Generated by Django 5.1.3 on 2024-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habits",
            options={"verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
        migrations.RenameField(
            model_name="habits",
            old_name="Reward",
            new_name="reward",
        ),
        migrations.AlterField(
            model_name="habits",
            name="pleasant_habit",
            field=models.BooleanField(
                default=True,
                help_text="Признак приятной привычки",
                verbose_name="Признак приятной привычки",
            ),
        ),
    ]
